sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  on_failure: change
node_js:
  - "5"
before_script:
  - npm prune
script: PUBLIC_PATH=/feedy npm run build
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
